FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json* ./
RUN npm ci || npm install

COPY prisma ./prisma
COPY nodemon.json tsconfig.json ./
RUN npm run db:generate

COPY src ./src
COPY docker-entrypoint.sh ./

EXPOSE 4000

CMD ["npm", "run", "dev"]
