export const BLOG_MODULE_CONFIG = {
  id: 'blog',
  title: 'Blog',
  description: 'Create and publish blog posts with SEO metadata.',
  defaultPageSize: 10,
} as const;

/** Default tech-focused categories shown in the blog post category dropdown. */
export const BLOG_SUGGESTED_CATEGORIES = [
  'Tech',
  'Engineering',
  'Software Development',
  'Web Development',
  'Frontend',
  'Backend',
  'Full Stack',
  'Mobile Development',
  'DevOps',
  'Cloud Computing',
  'AWS',
  'Azure',
  'Google Cloud',
  'AI & Machine Learning',
  'Data Science',
  'Cybersecurity',
  'Blockchain',
  'Internet of Things',
  'API',
  'Microservices',
  'System Design',
  'Database',
  'SQL',
  'NoSQL',
  'JavaScript',
  'TypeScript',
  'Python',
  'React',
  'Next.js',
  'Node.js',
  'Tutorial',
  'How-to Guide',
  'Best Practices',
  'Case Study',
  'Product',
  'SaaS',
  'Open Source',
  'Startup',
  'Career',
  'Interview Prep',
  'News',
  'Release Notes',
  'Review',
  'Architecture',
  'Performance',
  'Testing',
  'UI/UX',
  'Design',
] as const;
